export enum containerVariants {
    PT,
    BOX,
    BLOCK,
    WRAPPER,
    FLEXFIT,
    SKILLGRID,
    FULLWIDTH,
    FLEXBLOCK,
    FLEXAROUND,
    FLEXCENTER,
    LAYOUTGRID,
    HEROWRAPPER,
    FLEXBETWEEN,
}